name: Atualizar Blocklist

on:
  schedule:
    - cron: '0 3 * * *'  # Todos os dias às 03:00 UTC
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python e curl
        run: sudo apt update && sudo apt install -y python3 curl

      - name: Consolidar listas
        run: bash scripts/consolidar.sh

      - name: Gerar blocklist final
        run: python3 scripts/gerar.py

      - name: Fazer commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blocklists/*.txt
          git commit -m "🔄 Atualização automática" || echo 'Sem alterações'
          git push
